name: alefk
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  device_preview: ^1.2.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  iconly: ^1.0.1
  carousel_slider: ^5.0.0

  flutter_dash: ^1.0.0
  url_launcher: ^6.1.10
  dio: ^5.2.0
  awesome_dialog: ^3.2.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0
  talker_bloc_logger: ^4.8.0
  talker_flutter: ^4.8.0
  talker_dio_logger: ^4.8.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  go_router: ^15.1.1
  share_plus: ^10.0.1
  app_links: ^6.4.0
  scroll_date_picker: ^3.8.0

dev_dependencies:
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  flutter_flavorizr: ^2.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flavorizr:
  ide: "vscode"

  app:
    android:
      flavorDimensions: "app"
      defaultFlavor: customerDev
    ios:
      targets:
        Runner:
          bundleId: "com.example.customerDev"

  flavors:
    customerDev:
      app:
        name: "Customer Dev"
#        icon: "assets/icons/app_icon_customer_dev.png"
      android:
        applicationId: "com.example.customerDev"
      ios:
        bundleId: "com.example.customerDev"

    customerProd:
      app:
        name: "Customer"
#        icon: "assets/icons/app_icon_customer.png"
      android:
        applicationId: "com.example.customer"
      ios:
        bundleId: "com.example.customer"

    traderDev:
      app:
        name: "Trader Dev"
#        icon: "assets/icons/app_icon_trader_dev.png"
      android:
        applicationId: "com.example.traderDev"
      ios:
        bundleId: "com.example.traderDev"

    traderProd:
      app:
        name: "Trader"
#        icon: "assets/icons/app_icon_trader.png"
      android:
        applicationId: "com.example.trader"
      ios:
        bundleId: "com.example.trader"

    adminDev:
      app:
        name: "Admin Dev"
#        icon: "assets/icons/app_icon_admin_dev.png"
      android:
        applicationId: "com.example.adminDev"
      ios:
        bundleId: "com.example.adminDev"

    adminProd:
      app:
        name: "Admin"
#        icon: "assets/icons/app_icon_admin.png"
      android:
        applicationId: "com.example.admin"
      ios:
        bundleId: "com.example.admin"


flutter:


  uses-material-design: true
  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

