name: alefk
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  device_preview: ^1.2.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  iconly: ^1.0.1
  carousel_slider: ^5.0.0
  go_router: ^15.1.1
  flutter_dash: ^1.0.0
  url_launcher: ^6.1.10
  dio: ^5.2.0
  awesome_dialog: ^3.2.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0
  talker_bloc_logger: ^4.8.0
  talker_flutter: ^4.8.0
  talker_dio_logger: ^4.8.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

